### ISSUE TITLE
Make ClassToString print null values

### ISSUE THREAD

**Issue by ebelevics** [BreX900/data_class#17]
Thank you really for this simple yet useful package, I love that is preserves dart class models compared to other data class generators. What is missing, is that I don't see class null values. I suppose   ```void add(String field, Object? value) { if (value == null) return;``` is the one that causing it. Null is still a value, otherwise it seems like I don't have such parameter at all. You don't need to force it, just give an option to switch on or off for each generated `ClassToString`, idk in build.yaml file for example.
Thank you!

**Comment by BreX900** [comment]
@ebelevics You can `import 'package:class_to_string/class_to_flat_string.dart';` and have a custom ClassToString creator set up.
```dart
void main() {
  ClassToString.creator = (className, types) => NullableClassToIndentString(className, types ?? const []);

  // ...
}

class NullableClassToIndentString extends ClassToIndentString {
  NullableClassToIndentString(super.className, [super.types = const []]);
  
  void add(String field, Object? value) => add(field, value ?? 'null');
}
```

I'm considering adding a flag on the yaml file or a flag on `ClassToString`.
I'm also considering moving the `stringify_type: params | fields` option from the yaml file to the `ClassToString` class because the `toString` method is very subjective/personal so it should be customizable based on the developer and not on the package designer
I have to evaluate better
