### ISSUE TITLE
Fix mixin type

### ISSUE THREAD

**Issue by clragon** [BreX900/data_class#4]
First off, very nice package.

I noticed this in the generated code:
![image](https://user-images.githubusercontent.com/11785085/213324357-6aa7c14a-4056-4c73-b8c8-c0efc38887b1.png)

Would it not be possible to remove this, if we create the mixin with the correct type?

```dart
mixin _$Comment on Comment {
```

then, this getter and the cast is unnecessary.

**Comment by clragon** [comment]
I see that `freezed` also does not do this. then maybe this is simply a limitation of how code gen works.
I will close this issue.

**Comment by BreX900** [comment]
Let's say you can't write when it follows because it would cyclically depend on each other.
```dart
class Comment with _$Comment {
```
```dart
mixin _$Comment on Comment {
```

Also other packages like `frozen` and `built_value` implement the class you define by forcing you to use "their" generated class. This doesn't happen in this package so as to leave you with a classic constructor.

Also I could always override all the properties of your class and define them all in the generated `mixin` but you will have to give it @ovveride in each property but I want to avoid that.

I am writing this comment as documentation for other people who will be asking this same question
